on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ["e1", "e2"]
    environment: ${{ matrix.env }}
    steps:
    - name: new
      run: |
        echo "env: ${{ secrets.testit  }} - ${{ vars.testit }}"
