name: Dynamic Matrix Example

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Select the type of release bump'
        required: true
        type: 'choice'
        options:
          - patch
          - minor
          - major
          - rc
        default: rc
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: tag bump
      id: tag-bump
      shell: bash
      run: |
        # recent_tag=$(ls .git/refs/tags | sort -Vr | head -n1)
        recent_tag=$(curl -s "https://api.github.com/repos/${{ github.repository }}/tags" | grep '"name":' | sed -E 's/.*"name": "([^"]+)".*/\1/' | sort -Vr | head -n1)
        echo "--- $recent_tag"
        new_tag=$(bash .github/tag-bump.sh $recent_tag ${{ inputs.bump }})
        echo "new tag: $new_tag"
        echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

    - name: changelog-ci
      uses: saadmk11/changelog-ci@v1.1.2
      id: changelog-ci
      with:
        release_version: ${{ steps.tag-bump.outputs.new_tag }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.tag-bump.outputs.new_tag }}
        release_name: Release ${{ steps.tag-bump.outputs.new_tag }}
        body: ${{ steps.changelog-ci.outputs.changelog }}

    # - name: issue
    #   uses: sunny-1651/manual-approval@checkin
    #   with:
    #     secret: ${{ steps.generate_token.outputs.token }}
    #     approvers: sunny-1651
    #     minimum-approvals: 1
    #     target-repository: first_go_project
    #     target-repository-owner: sunny-1651

